#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderFx.Integration.Model.Messages
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("AnalyzeSentiment")]
	public partial class AnalyzeSentimentRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Text = "Text";
			public const string ModelId = "ModelId";
			public const string Language = "Language";
		}
		
		public const string ActionLogicalName = "AnalyzeSentiment";
		
		public string Text
		{
			get
			{
				if (Parameters.Contains("text"))
				{
					return ((string)(Parameters["text"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				Parameters["text"] = value;
			}
		}
		
		public string ModelId
		{
			get
			{
				if (Parameters.Contains("modelId"))
				{
					return ((string)(Parameters["modelId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				Parameters["modelId"] = value;
			}
		}
		
		public string Language
		{
			get
			{
				if (Parameters.Contains("language"))
				{
					return ((string)(Parameters["language"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				Parameters["language"] = value;
			}
		}
		
		public AnalyzeSentimentRequest()
		{
			RequestName = "AnalyzeSentiment";
			Text = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("AnalyzeSentiment")]
	public partial class AnalyzeSentimentResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string DocumentsCores = "DocumentsCores";
			public const string Sentences = "Sentences";
			public const string Sentiment = "Sentiment";
		}
		
		public const string ActionLogicalName = "AnalyzeSentiment";
		
		public AnalyzeSentimentResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity DocumentsCores
		{
			get
			{
				if (Results.Contains("documentScores"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(Results["documentScores"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				Results["DocumentsCores"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection Sentences
		{
			get
			{
				if (Results.Contains("sentences"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(Results["sentences"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				Results["Sentences"] = value;
			}
		}
		
		public string Sentiment
		{
			get
			{
				if (Results.Contains("sentiment"))
				{
					return ((string)(Results["sentiment"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				Results["Sentiment"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
