using System.Text;
using PathfinderFx.Model;

namespace PathfinderFx.Helper;

public static class DataGenHelper
{
    
    
    //return a random decimal between 0.0 and 100.00 as a string
    internal static string GenerateRandomDecimalString()
    {
        var random = new Random();
        var randomDecimal = random.NextDouble() * 100;
        return randomDecimal.ToString("0.00");
    }
    
    internal static decimal GenerateRandomDecimal()
    {
        var random = new Random();
        return new decimal(random.NextDouble() * 100);
    }

    //generate a random 2 word name as a string
    internal static string GenerateRandomName()
    {
        var random = new Random();
        var randomName = $"{RandomWord(random)} {RandomWord(random)}";
        return randomName;
    }

    private static string RandomWord(Random random)
    {
        //generate a random word from a list of words
        var words = new List<string>
        {
            "Able",
            "Acid",
            "Acre",
            "Acts",
            "Aged",
            "Ago",
            "Aid",
            "Aim",
            "Air",
            "Ajar",
            "Alarm",
            "Alias",
            "Alibi",
            "Alien",
            "Alley",
            "Aloe",
            "Alone",
            "Amen",
            "Amend",
            "Amp",
            "Ample",
            "Amuse",
            "Angel",
            "Anger",
            "Angle",
            "Angry",
            "Animal",
            "Ankle",
            "Annoy",
            "Annual",
            "Answer",
            "Ant",
            "Ante",
            "Anti",
            "Antic",
            "Ants",
            "Anvil",
            "Any",
            "Ape",
            "Apex",
            "Aplomb",
            "Appeal",
            "Apple",
            "Apply",
            "Apron",
            "Apt",
            "Aqua",
            "Arbor",
            "Arc",
            "Arcade",
            "Arch",
            "Arched",
            "Area",
            "Arid",
            "Arm",
            "Army",
            "Aroma",
            "Array",
            "Arrow",
            "Arson",
            "Art",
            "Ash",
            "Aspen",
            "Assist",
            "Aster",
            "Ate",
            "Atom",
            "Attic",
            "Audio",
            "Audit",
            "Auger",
            "Aunt",
            "Auntie",
            "Aura",
            "Auto",
            "Autumn",
            "Ava",
            "Avenue",
            "Avert",
            "Avid",
            "Avoid",
            "Avow",
            "Await",
            "Awake",
            "Award",
            "Aware",
            "Awash",
            "Away",
            "Awe",
            "Awful",
            "Awkward",
            "Awning",
            "Axe",
            "Aye",
            "Babe",
            "Baby",
            "Back",
            "Bacon",
            "Bad",
            "Badge",
            "Bag",
            "Bagel",
            "Baggy",
            "Bail",
            "Bait",
            "Bake",
            "Baker",
            "Bald",
            "Cake",
            "Calf",
            "Call",
            "Calm",
            "Calve",
            "Camel",
            "Camp",
            "Can",
            "Cane",
            "Cant",
            "Door",
            "Dope",
            "Dose",
            "Dot",
            "Dough",
            "Dove",
            "Down",
            "Dour",
            "Dove",
            "Eagle",
            "Ear",
            "Earn",
            "Earth",
            "Ease",
            "East",
            "Easy",
            "Eat",
            "Eave",
            "Ebb",
            "Echo",
            "Edge",
            "Eel",
            "Egg",
            "Ego",
            "Fan",
            "Fancy",
            "Fang",
            "Food",
            "Fool",
            "Foot",
            "For",
            "Ford",
            "Form",
            "Fort",
            "Fork",
            "Foul",
            "Four",
            "Fox",
            "Frog",
            "Gag",
            "Gain",
            "Gait",
            "Gala",
            "Gale",
            "Gall",
            "Game",
            "Gang",
            "Gap",
            "Gear",
            "Gee",
            "Gel",
            "Gun",
            "Gut",
            "Gym",
            "Habit",
            "Hack",
            "Hail",
            "Hair",
            "Half",
            "Heal",
            "Heap",
            "Hear",
            "Hope",
            "Hose",
            "Host",
            "Hot",
            "Hour",
            "Halo",
            "Halt",
            "Hen",
            "Herd",
            "Hero",
            "Golf",
            "Gone",
            "Good",
            "Goof",
            "Gore",
            "Hose",
            "Host",
            "Hot",
            "Hour",
            "Idea",
            "Idle",
            "Idol",
            "Igloo",
            "Icy",
            "Juice",
            "Juke",
            "Jury",
            "Just",
            "Kale",
            "Keg",
            "Kept",
            "Kite",
            "Koala",
            "Knot",
            "Knee",
            "Lace",
            "Lack",
            "Lad",
            "Leaf",
            "Lean",
            "Leap",
            "Lear",
            "Make",
            "Male",
            "Mall",
            "Malt",
            "Mind",
            "Monk",
            "Mood",
            "Moon",
            "Moose",
            "Mop",
            "Moral",
            "Name",
            "Nail",
            "Nap",
            "Nape",
            "Napkin",
            "Need",
            "Nest",
            "Net",
            "Old",
            "Olive",
            "Omen",
            "One",
            "Open",
            "Oath",
            "Oats",
            "Ogle",
            "Oily",
            "Pace",
            "Pack",
            "Pad",
            "Pail",
            "Pain",
            "Pair",
            "Palm",
            "Pea",
            "Peak",
            "Pear",
            "Peek",
            "Peel",
            "Peg",
            "Quiz",
            "Quota",
            "Quote",
            "Quack",
            "Quail",
            "Rain",
            "Rake",
            "Rat",
            "Real",
            "Reap",
            "Rear",
            "Reed",
            "Reef",
            "Rust",
            "Sack",
            "Sail",
            "Sake",
            "Sale",
            "Seal",
            "Seat",
            "Seek",
            "Side",
            "Silo",
            "Silt",
            "Soak",
            "Soap",
            "Sole",
            "Soot",
            "Tack",
            "Taco",
            "Tact",
            "Tail",
            "Take",
            "Tale",
            "Tame",
            "Team",
            "Tear",
            "Tee",
            "Toad",
            "Toll",
            "Tomb",
            "Unit",
            "Urn",
            "Use",
            "Ugly",
            "Vain",
            "Vale",
            "Vamp",
            "Vane",
            "Veal",
            "Veil",
            "Vest",
            "Vote",
            "Wade",
            "Wack",
            "Wade",
            "Wage",
            "Wail",
            "Weal",
            "Wean",
            "Wear",
            "Weed",
            "Wind",
            "Wing",
            "Yack",
            "Yam",
            "Yank",
            "Yard",
            "Year",
            "Yell",
            "Yelp",
            "Yoga",
            "Yolk",
            "Yule",
            "Zack",
            "Zany",
            "Zap",
            "Zebra",
            "Zero",
            "Zest",
            "Zig",
            "Zinc",
            "Zip",
            "Zone",
            "Zoo",
        };
        return words[random.Next(words.Count)];
    }

    public static string GetRandomUnit()
    {
        //select a random unit from the enum Unit and return it as a string
        var values = Enum.GetValues(typeof(DeclaredUnit));
        var random = new Random();
        var randomUnit = (DeclaredUnit)(values.GetValue(random.Next(values.Length)) ?? DeclaredUnit.Kilogram);
        return Enum.GetName(typeof(DeclaredUnit), randomUnit) ?? "metricTon";
    }

    public static string GenerateRandomCompanyId()
    {
        //create a random certificate id string
        var random = new Random();
        var randomCertificateId = $"{random.Next(10000000, 99999999)}";
        return randomCertificateId;
    }

    //return a random company name as a string
    public static string GenerateRandomCompanyName()
    {
        var random = new Random();
        var randomCompanyName = $"{RandomWord(random)}" + " " + GetRandomCompanyPostfix();
        return randomCompanyName;
    }

    private static string GetRandomCompanyPostfix()
    {
        var postFix = new List<string>
        {
            "Inc",
            "Corp",
            "Ltd",
            "LLC",
            "GmbH",
            "AG",
            "S.A.",
            "S.p.A.",
            "S.L.",
            "S.L.U.",
            "S.A.S."
        };

        var random = new Random();
        return postFix[random.Next(postFix.Count)];
    }

    public static string GenerateRandomProductId()
    {
        //create a random product id string that is 16 characters long with a random 2 letter prefix and 10 random numbers separated by hyphens
        var random = new Random();  
        var randomProductId = $"{RandomWord(random)[..2]}-{random.Next(1000000000, unchecked((int)9999999999))}";
        return randomProductId;

    }
}