#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderFx.Integration.Model.OptionSets
{
	
	
	/// <summary>
	/// Indicator of approval of MSM entity.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_ApprovalStatus
	{
		
		/// <summary>
		/// Approved
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadata("Approved", 1, null, "Approved")]
		Approved = 700610001,
		
		/// <summary>
		/// Pending
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadata("Pending", 0, null, "Pending")]
		Pending = 700610000,
	}
}
#pragma warning restore CS1591
