#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderFx.Integration.Model.OptionSets;

/// <summary>
/// Power Pages Languages
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
public enum PowerPageLanguages
{
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Arabic", 0, "#0000ff")]
	Arabic = 1025,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Basque - Basque", 1, "#0000ff")]
	BasqueBasque = 1069,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Bulgarian - Bulgaria", 2, "#0000ff")]
	BulgarianBulgaria = 1026,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Catalan - Catalan", 3, "#0000ff")]
	CatalanCatalan = 1027,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Chinese - China", 4, "#0000ff")]
	ChineseChina = 2052,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Chinese - Hong Kong SAR", 5, "#0000ff")]
	ChineseHongKongSar = 3076,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Chinese - Traditional", 6, "#0000ff")]
	ChineseTraditional = 1028,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Croatian - Croatia", 7, "#0000ff")]
	CroatianCroatia = 1050,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Czech - Czech Republic", 8, "#0000ff")]
	CzechCzechRepublic = 1029,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Danish - Denmark", 9, "#0000ff")]
	DanishDenmark = 1030,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Dutch - Netherlands", 10, "#0000ff")]
	DutchNetherlands = 1043,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("English", 11, "#0000ff")]
	English = 1033,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Estonian - Estonia", 12, "#0000ff")]
	EstonianEstonia = 1061,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Finnish - Finland", 13, "#0000ff")]
	FinnishFinland = 1035,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("French - France", 14, "#0000ff")]
	FrenchFrance = 1036,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Galician - Spain", 15, "#0000ff")]
	GalicianSpain = 1110,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("German - Germany", 16, "#0000ff")]
	GermanGermany = 1031,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Greek - Greece", 17, "#0000ff")]
	GreekGreece = 1032,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Hebrew", 18, "#0000ff")]
	Hebrew = 1037,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Hindi - India", 19, "#0000ff")]
	HindiIndia = 1081,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Hungarian - Hungary", 20, "#0000ff")]
	HungarianHungary = 1038,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Indonesian - Indonesia", 21, "#0000ff")]
	IndonesianIndonesia = 1057,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Italian - Italy", 22, "#0000ff")]
	ItalianItaly = 1040,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Japanese - Japan", 23, "#0000ff")]
	JapaneseJapan = 1041,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Kazakh - Kazakhstan", 24, "#0000ff")]
	KazakhKazakhstan = 1087,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Korean - Korea", 25, "#0000ff")]
	KoreanKorea = 1042,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Latvian - Latvia", 26, "#0000ff")]
	LatvianLatvia = 1062,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Lithuanian - Lithuania", 27, "#0000ff")]
	LithuanianLithuania = 1063,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Malay - Malaysia", 28, "#0000ff")]
	MalayMalaysia = 1086,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Norwegian (Bokmål) - Norway", 29, "#0000ff")]
	NorwegianBokmLNorway = 1044,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Polish - Poland", 30, "#0000ff")]
	PolishPoland = 1045,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Portuguese - Brazil", 31, "#0000ff")]
	PortugueseBrazil = 1046,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Portuguese - Portugal", 32, "#0000ff")]
	PortuguesePortugal = 2070,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Romanian - Romania", 33, "#0000ff")]
	RomanianRomania = 1048,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Russian - Russia", 34, "#0000ff")]
	RussianRussia = 1049,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Serbian (Cyrillic) - Serbia", 35, "#0000ff")]
	SerbianCyrillicSerbia = 3098,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Serbian (Latin) - Serbia", 36, "#0000ff")]
	SerbianLatinSerbia = 2074,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Slovak - Slovakia", 37, "#0000ff")]
	SlovakSlovakia = 1051,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Slovenian - Slovenia", 38, "#0000ff")]
	SlovenianSlovenia = 1060,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Spanish (Traditional Sort) - Spain", 39, "#0000ff")]
	SpanishTraditionalSortSpain = 3082,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Swedish - Sweden", 40, "#0000ff")]
	SwedishSweden = 1053,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Thai - Thailand", 41, "#0000ff")]
	ThaiThailand = 1054,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Turkish - Türkiye", 42, "#0000ff")]
	TurkishTRkiye = 1055,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Ukrainian - Ukraine", 43, "#0000ff")]
	UkrainianUkraine = 1058,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Vietnamese - Vietnam", 44, "#0000ff")]
	VietnameseVietnam = 1066,
}
#pragma warning restore CS1591
