#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderFx.Integration.Model.OptionSets;

/// <summary>
/// Identifies where the social profile originated from, such as Twitter, or FaceBook.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
public enum SocialProfile_Community
{
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Apple Messages For Business", 11, "#0000ff")]
	AppleMessagesForBusiness = 16,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Cortana", 0, "#0000ff")]
	Cortana = 5,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Direct Line", 1, "#0000ff")]
	DirectLine = 6,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Direct Line Speech", 3, "#0000ff")]
	DirectLineSpeech = 8,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Email", 4, "#0000ff")]
	Email = 9,
		
	/// <summary>
	/// Facebook item.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Facebook", 15, "", "Facebook item.")]
	Facebook = 1,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Google\'s Business Messages", 12, "#0000ff")]
	GoogleSBusinessMessages = 17,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("GroupMe", 5, "#0000ff")]
	Groupme = 10,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Kik", 6, "#0000ff")]
	Kik = 11,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Line", 13, "#0000ff")]
	Line = 3,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Microsoft Teams", 2, "#0000ff")]
	MicrosoftTeams = 7,
		
	/// <summary>
	/// Other default
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Other", 17, "", "Other default")]
	Other = 0,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Skype", 8, "#0000ff")]
	Skype = 13,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Slack", 9, "#0000ff")]
	Slack = 14,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Telegram", 7, "#0000ff")]
	Telegram = 12,
		
	/// <summary>
	/// Twitter.
	/// </summary>
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Twitter", 16, "", "Twitter.")]
	Twitter = 2,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("Wechat", 14, "#0000ff")]
	Wechat = 4,
		
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadata("WhatsApp", 10, "#0000ff")]
	Whatsapp = 15,
}
#pragma warning restore CS1591
