#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathfinderFx.Integration.Model.OptionSets
{
	
	
    /// <summary>
    /// Options for Template Default View
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    public enum TemplateDefaultView
    {
		
        /// <summary>
        /// Grid View
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Grid View", 1, "#0000ff", "Grid View")]
        GridView = 2,
		
        /// <summary>
        /// List View
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("List View", 2, "#0000ff", "List View")]
        ListView = 3,
		
        /// <summary>
        /// Tiles View
        /// </summary>
        [System.Runtime.Serialization.EnumMemberAttribute()]
        [OptionSetMetadataAttribute("Tiles View", 0, "#0000ff", "Tiles View")]
        TilesView = 1,
    }
}
#pragma warning restore CS1591